### ISSUE TITLE
Ribosomengröße implementieren

### ISSUE THREAD

**Issue by Nexia23** [Nexia23/fachkurs_2016_project#1]
- [x] Nachschauen, wie groß Ribosomen sind (wie viel Basen sind blockiert)
- [x] Implementieren
- [x] ins laufende Programm integrieren

**Comment by Nexia23** [comment]
Es sind ca. 10 Codons besetzt und zwar wahrscheinlich hinter der A-site
Referenzpaper : PMCID: PMC454858

**Comment by derHahn** [comment]
Das ist ja quasi gemacht, oder?
