### ISSUE TITLE
Debuggen - Fehler beheben

### ISSUE THREAD

**Issue by derHahn** [Nexia23/fachkurs_2016_project#11]
Ich hab Euch mit dem Tag `!Jens!` Kommentare in den Code eingefügt, bitte die Fehler beseitigen. Bei Fragen melden!!

**Comment by derHahn** [comment]
Ausserdem hab ich das Label "Kann warten" eingeführt, diese Issues sind erst mal nicht so wichtig!

**Comment by Nexia23** [comment]
*Jens!: Und wer rauemt das ribosom weg das occupy() setzt? da brauchen wir auch ein entkoppel()
 *self.occupy(mrna, i+1)  
  *!Maxim!:falls ich die Frage richtig verstehe->occupy function setzt die i-10 auf 0 somit ist es doch bewegt

**Comment by derHahn** [comment]
Recht haste, alles gut! :+1: 
Sehr gut, jetzt also weiter mit richtigen Aufgaben!
