### ISSUE TITLE
START codon

### ISSUE THREAD

**Issue by Nexia23** [Nexia23/fachkurs_2016_project#2]
- [x] Rausfinden, warum es START codons gibt
  - Kann das Ribosom trotzdem binden?
  - Kann das Ribosom weiter laufen?
  - Was passiert, wenn kein START codon da ist?
- [x] Wie können wir das einbauen?

**Comment by derHahn** [comment]
1. Es wird einfach kein Protein synthetisiert
2. Funktion `move()` und `bind()` einfügen
