### ISSUE TITLE
Update Verfahren optimieren

### ISSUE THREAD

**Issue by Nexia23** [Nexia23/fachkurs_2016_project#5]
- [ ] Update ändern für Sekunden-Zeitschritt
- [ ] Randomize-Verfahren implementieren
  - bisher werden die Mrnas nacheinander anhand ihrer Id aufgerufen und die Poissongl. ausgeführt.
    Dies bedeutet, dass die ersten Mrnas eine höhere Wahrscheinlichkeit haben, sich mit einem 
    Ribosom zu binden ( da mehr frei sind ) als die letzten Mrnas ( mehr Ribosome schon gebunden).

**Comment by derHahn** [comment]
Ich versteh den Issue nicht ganz, kannst Du den Punkte etwas mehr Detail geben? :question:  
Ausserdem habe ich Euren Code etwas repariert, also bitte **pullen** bevor ihr programmiert!!  
Bis später
@IGotMyMojoWorking @LenaSch @Nexia23

**Comment by derHahn** [comment]
Ok, verstehe, da würde ich 2 Issues draus machen:
1. Bewegung von Ribosomen limitieren #8 
2. Ribosomen auf mRNA random auswählen (trotzdem alle abfragen!) #9

**Comment by derHahn** [comment]
Aufgeteilt in 2 Issues, der hier kann wech
