### ISSUE TITLE
Ribosome movement step size

### ISSUE THREAD

**Issue by LenaSch** [Nexia23/fachkurs_2016_project#7]
- [x] Ribosom soll in 1er-Schritten wandern bis Startcodon gefunden ist, erst dann in 3er-Schritten

**Comment by derHahn** [comment]
Auch dieser Issue kann noch etwas warten, zur Zeit können wir ja noch ordentlich 3*n lange mRNAs erwarten!

**Comment by Nexia23** [comment]
problem gelöst ansich bisschen cheeky
