### ISSUE TITLE
Zufällige Reihenfolge der Ribosomenabfrage

### ISSUE THREAD

**Issue by derHahn** [Nexia23/fachkurs_2016_project#9]
Die Ribosomen sollen nicht von 5' zu 3' nacheinander bewegt werden, sondern zufällig ausgewählt werden! 

Das kann noch etwas warten, dafür muss man einiges umbauen, schließlich hört die `move()` Funktion zur Zeit auf, wenn sie ein initialisiertes Ribosom trifft und wechselt zu `elongate()`
- [x] Auswahlfunktion schreiben (verwendet ``numpy.random`!!)
- [x] Funktion vorschalten (vor `move()` und `elongate()`)

**Comment by Nexia23** [comment]
mit random.shuffle erledigt
